import React from "react";

import ParagraphUi from "src/components/ui/fonts/paragraph";
import H3Ui from "src/components/ui/fonts/h3";
import GoogleButton from "../ui/googleButton";

import styles from "./index.module.scss";

const LogIn = () => {
  return (
    <div className={styles.login}>
      <H3Ui>Log in</H3Ui>
      <div>
        <GoogleButton>Continue with Google</GoogleButton>
      </div>
      <ParagraphUi>
        By signing up you acknowledge that content is generated by AI and agree to our terms of use
        & privacy policy.
      </ParagraphUi>
    </div>
  );
};

export default LogIn;
