import React from "react";

import ParagraphUi from "src/components/ui/fonts/paragraph";
import H3Ui from "src/components/ui/fonts/h3";
import GoogleButton from "../ui/googleButton";
import SelectRole from "../ui/selectRole";

import styles from "./index.module.scss";

const SingUp = () => {
  return (
    <div className={styles.singup}>
      <H3Ui>Welcome to Qualyfid!</H3Ui>
      <ParagraphUi>Sing up and get first 100 credits for free</ParagraphUi>
      <SelectRole />
      <div>
        <GoogleButton>Continue with Google</GoogleButton>
      </div>
      <ParagraphUi>
        By signing up you acknowledge that content is generated by AI and agree to our terms of use
        & privacy policy.
      </ParagraphUi>
    </div>
  );
};

export default SingUp;
